# Generated by Django 5.1.2 on 2024-11-06 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noivos', '0002_convidados'),
    ]

    operations = [
        migrations.AddField(
            model_name='convidados',
            name='maximo_acompanhantes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='convidados',
            name='nome_convidado',
            field=models.CharField(default='Nome Padrão', max_length=255),
        ),
        migrations.AddField(
            model_name='convidados',
            name='status',
            field=models.CharField(choices=[('AC', 'Aguardando confirmação'), ('C', 'Confirmado'), ('R', 'Recusado')], default='AC', max_length=2),
        ),
        migrations.AddField(
            model_name='convidados',
            name='token',
            field=models.CharField(blank=True, max_length=25, unique=True),
        ),
        migrations.AddField(
            model_name='convidados',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
