# Generated by Django 5.1.2 on 2024-11-06 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noivos', '0003_convidados_maximo_acompanhantes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convidados',
            name='nome_convidado',
            field=models.CharField(default='Nome Padrão', max_length=100),
        ),
    ]
