# Generated by Django 5.1.2 on 2024-11-06 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noivos', '0005_presentes_reservado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='convidados',
            name='adicionado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='noivos.convidados'),
        ),
    ]
